# SPDX-FileCopyrightText: 2026 Julien Y. Dutheil <jy.dutheil@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
    - id: reuse
