# SPDX-FileCopyrightText: 2026 Julien Y. Dutheil <jy.dutheil@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

theme: jekyll-theme-tactile
title: MafFilter
description: a genome alignment processor
show_downloads: true
share: true
